itamarst/eliot

docs/source/news.rst
docs/source/types.rst
eliot/_validation.py
eliot/tests/test_validation.py

Pull request for issue #144.
I'm not sure if there should be some checking of the positional arguments to `fields`, making sure they're `Field` instances or such?

Allow passing existing `Field`s to `fields`

---

docs/source/messages.rst
docs/source/news.rst
docs/source/twisted.rst
eliot/_output.py
eliot/_traceback.py
eliot/tests/test_output.py
eliot/tests/test_testing.py
eliot/tests/test_traceback.py
eliot/tests/test_twisted.py

Rip out ``system`` argument to traceback functions

---

docs/source/news.rst
eliot/testing.py
eliot/tests/test_testing.py

Fixes #153 
This only handles the synchronous case.  If someone is using `@validateLogging` with Twisted and returns a `Deferred` from their test method ... well, things get harder.  Maybe that case is worth fixing too but maybe it's worth fixing *separately*.
I also disabled unflushed traceback checking for skipped tests on the grounds that if your validation function does not run there's a reasonable chance there could be a traceback you expected to be logged and then get flushed - but you didn't get a chance to flush it.

Validate logging skip interaction 153

---

docs/source/news.rst
eliot/_output.py
eliot/tests/test_output.py

Better handling for exceptions in destinations - fixes #45

---

docs/source/news.rst
eliot/tests/test_twisted.py
eliot/twisted.py

#168 talks about logging JSON when redirecting trial output. It proposes a fuller, better solution, which is having a "pure" eliot log. This patch is an interim step: it does what the current logging does, except it formats it with `json.dumps` rather than `pformat`.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/eliot/179)

Log JSON when redirecting trial output

---

eliot/_message.py
eliot/tests/test_message.py
setup.py

Adds a new `LoggedMessage` class to `eliot._message`. This class knows how to turn a message into a dict and how to turn a dict into a message. It's an incremental step toward #181. Then next step would be adding something that takes a stream of `LoggedMessage` objects and constructs a `LoggedAction`.
The `LoggedMessage` class dignifies `timestamp`, `task_uuid`, and `task_level` with their own attributes and docstrings. As a late call, I made `task_level` actually be a `TaskLevel` object, to keep up with the "structured data" leitmotif.
The patch also separates figuring out what we should write from the actual writing by adding a `_freeze` method to `Message`.
I've deliberately left `eliot.testing.LoggedMessage` untouched, because I wasn't sure what to do with it.
[<img …

Reversible logging for messages

---

eliot/_action.py
eliot/_message.py
eliot/tests/test_action.py
setup.py

Make `TaskLevel` immutable, moving the mutating part up to `Action`, which now knows what the last task it logged was.
Also adds some tests that use `hypothesis`. This slows the test suite a bit (~0.4s on my laptop), because although it looks like I'm adding two tests I'm actually adding two hundred. I'm happy to ditch hypothesis and rewrite them the normal way.
Although not strictly necessary for the parsing work I have planned in #188, this at least helps my thinking about the problem.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/eliot/189)

Make TaskLevel immutable

---

docs/source/news.rst
eliot/_message.py
eliot/tests/test_message.py

Fixes #197.
This means messages logged outside of an action get their own UUID:
```
$ .tox/py27/bin/python examples/rometrip_messages.py | .tox/py27/bin/eliot-tree | grep -v timestamp
81faaeaf-6f75-4eeb-8405-a43e1036accb
+-- honeymoon@1
|-- family: [u'Mrs. Casaubon', u'Mr. Casaubon']
90fcf8cb-fcda-458a-ba43-db4fdb8b0255
+-- place:visited@1
|-- person: Mrs. Casaubon
|-- place: Rome, Italy
e4ff0526-ce1b-443c-bf0c-d7e296b78cba
+-- place:visited@1
|-- person: Mrs. Casaubon
|-- place: Vatican Museum
adb66e53-2a24-466b-aafe-b894a6ce4b29
+-- place:visited@1
|-- person: Mrs. Casaubon
|-- place: Statue #1
3f1f803c-4330-4c8a-a211-a9db797db4d0
+-- place:visited@1
|-- person: Mrs. Casaubon
|-- place: Statue #2
086dcedb-190b-42fd-a8fd-704ec36e22ba
+-- place:visited@1
|-- person: Mr. Casaubon
|-- …
```

Get rid of the default action

---

eliot/tests/test_output.py

https://github.com/ClusterHQ/eliot/pull/195 and https://github.com/ClusterHQ/eliot/pull/198 together break the tests. #195 assumes that the two error messages share the same task, and #198 makes them completely independent.
Since sharing the same task is not actually part of the expected behaviour, the simplest solution is to relax the assertion.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/eliot/199)

Don't test task_uuid and task_level values

---

eliot/_action.py
eliot/_message.py
eliot/_output.py
eliot/_traceback.py
eliot/_validation.py
eliot/testing.py

Rather than using anything nice like Python 3.4's `enum` or `twisted.python.constants`, I've just defined a bunch of variables with similar-looking names. I think this makes the code more readable and makes some of the structure of eliot more explicit.
I haven't updated usage in tests, but can if you'd like.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/eliot/200)

Define constants for field names and statuses

---

eliot/prettyprint.py
eliot/tests/test_prettyprint.py

Fixes #213.
The goal is to make the human task of copy/pasting the UUID on its own much simpler.

Change the output of task level to make it more clearly separate from the UUID

---

eliot/_action.py
eliot/_message.py
eliot/_parse.py
eliot/tests/strategies.py
eliot/tests/test_action.py
eliot/tests/test_parse.py
setup.py

Part 1 out of 2 of parsing messages into a tree. This branch adds code which allows parsing messages with the same task UUID into a tree object, a `eliot._parse.Task`.
This builds on #227 which should be reviewed first.
Next step will be parsing unrelated messages into a forest, in #228.

Parse messages into a tree

---

eliot/_parse.py
eliot/tests/strategies.py
eliot/tests/test_parse.py

Fixes #228.
1. Added concept of completeness to task-specific (==tree of actions parser) `Task`. A ``Task` is complete if all its messages have been parsed.
2. Added a new class `Parser` which parses messages into a forest of actions, i.e. multiple `Task` instances one per task UUID.
3. Added a higher-level API for parsing streams of messages.
4. Changed `hypothesis` strategy for generating UUIDs so that it generates them more randomly; previous implementation resulted in repeated UUIDs.

Parse messages into a forest of Tasks

---

docs/source/news.rst
eliot/_traceback.py
eliot/_validation.py
eliot/tests/test_action.py
eliot/tests/test_traceback.py
eliot/tests/test_validation.py

Fix validation of extracted exception fields.

---

docs/source/generating/threads.rst
docs/source/news.rst
eliot/__init__.py
eliot/_action.py
eliot/tests/test_action.py
examples/cross_thread.py

Easy API for having context span threads

---

docs/source/news.rst
eliot/prettyprint.py
eliot/tests/test_prettyprint.py

eliot-prettyprint no longer dies on non-JSON lines

---

docs/source/generating/actions.rst

Adds an explicit example of "code within the context block that is run after the action is finished will still be in that action's context."

Clarify behavior of Non-Finishing Contexts

---

docs/source/news.rst
eliot/testing.py
eliot/tests/test_testing.py

Fixes #373.
I believe start messages are already covered by the existing code in `assertHasAction`, where missing start messages will result in empty list of messages, and there's already logic for that with a human-readable message.
@exarkun

Better error message for missing end messages

---

docs/source/generating/index.rst
docs/source/generating/testing.rst
docs/source/generating/types.rst
docs/source/news.rst
eliot/testing.py
eliot/tests/test_testing.py

Fixes #364.
Also makes testing documentation not dependent on type system.

Lower-level API for capturing logs during tests

---

docs/source/generating/twisted.rst
docs/source/news.rst
eliot/__init__.py
eliot/_generators.py
eliot/tests/test_generators.py
eliot/tests/test_twisted.py
eliot/twisted.py

Fixes #259 
In addition to a decorator for plain old generators, this also introduces the tiny extra helper necessary to get Twisted's `inlineCallbacks` playing nicely with Eliot.  This takes the form of a new decorator that just applies both `inlineCallbacks` and the generator decorator being introduced.
Suggestions for better names for any of this welcome.  Let me know if there's any other structural work to be done (docs or whatever).
This work made possible by https://leastauthority.com/

Add context-preserving decorator for generators

---

CONTRIBUTING.md
docs/source/generating/actions.rst
eliot/__init__.py
eliot/_action.py
eliot/_generators.py
eliot/tests/test_generators.py
eliot/tests/test_twisted.py
eliot/twisted.py

OK, so I guess for this to be merged I'd like:
Fixes #259.

Generator decorator for inlineCallbacks

---

eliot/_validation.py

Fix simple typo: succesful -> successful

---

eliot/json.py

With `numpy==1.21.4`, I get the following warning when logging an array:
```
/home/kale/.local/share/miniconda/envs/aars/lib/python3.9/site-packages/eliot/json.py:22: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
if isinstance(o, (numpy.bool, numpy.bool_)):
```
It seems that `np.bool` is now just an alias for `bool`, so there's no reason to include it in this `isinstance()` check.

Remove deprecated np.bool alias

---

.github/workflows/main.yml
docs/source/news.rst
eliot/tests/test_json.py
setup.py
tox.ini

No changes needed, just running tests.

Python 3.13 support

---

.github/workflows/main.yml
README.rst
benchmarks/serialization_complex.py
docs/source/news.rst
eliot/json.py
eliot/tests/test_json.py
setup.py
tox.ini

Based on code from #511 (originally written by @antonkulaga).

More json encodings
