itamarst/eliot

MANIFEST.in, requirements-dev.txt
=> Include examples in sdist, get rid of unnecessary requirements-dev.txt - fixes #140

docs/source/actions.rst, docs/source/fields.rst
=> Try to make actions and tasks documentation clearer

eliot/tests/test_logwriter.py, tox.ini
=> Tests for vewer version of Twisted

docs/source/types-testing.rst
=> Add missing parameter to documentation example

docs/source/news.rst, eliot/_output.py, eliot/tests/test_logwriter.py, eliot/tests/test_output.py
=> Flush in FileDestination

.gitignore, eliot/_output.py, eliot/tests/test_output.py
=> Include timestamp in eliot:destinatinon_failure

eliot/tests/strategies.py, eliot/tests/test_action.py
This is so I can re-use them in other code.
Also, make them lower case.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/eliot/204)
=> Move strategies to their own module

docs/source/index.rst, docs/source/news.rst, docs/source/reading.rst, eliot/_bytesjson.py, eliot/_output.py, eliot/filter.py, eliot/prettyprint.py, eliot/tests/test_filter.py, eliot/tests/test_prettyprint.py, setup.py
=> Command-line utility to make messages easier to read

docs/source/index.rst, docs/source/journald.rst, docs/source/news.rst, eliot/journald.py, eliot/tests/test_journald.py, examples/journald.py, setup.py, tox.ini
Fixes #207.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/eliot/210)
=> Native Journald support

docs/source/news.rst, docs/source/output.rst, docs/source/twisted.rst, eliot/__init__.py, eliot/logwriter.py, eliot/tests/test_logwriter.py, examples/logfile.py
Fixes #216.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/eliot/217)
=> Make ThreadedFileWriter more generic so it can e.g. be used with JournaldDestination

eliot/_message.py, eliot/tests/strategies.py, eliot/tests/test_action.py, setup.py
=> Don't feed UUID and pvector to WrittenMessage.from_dict

eliot/tests/strategies.py, setup.py
New Hypothesis has `uuids` as a built-in. Use that.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/eliot/234)
=> Use built-in uuid from hypothesis 1.14

docs/source/news.rst, eliot/journald.py, eliot/tests/test_journald.py
=> Fix journald to work on Python 3.

.travis.yml, README.rst, docs/source/news.rst, eliot/_traceback.py, setup.py, tox.ini
=> Python 3.5 support

docs/source/news.rst, eliot/_traceback.py, eliot/_util.py, eliot/prettyprint.py, eliot/tests/test_prettyprint.py, eliot/tests/test_util.py, tox.ini
=> Pretty-print does better with conveying field value structure

eliot/_output.py, eliot/_validation.py, eliot/testing.py, eliot/tests/test_action.py, setup.py
Fixes #120.
Too tired to do real coding at the moment...
=> Drop usage of characteristic and namedtuple.

docs/source/news.rst, eliot/_validation.py, eliot/tests/test_validation.py
=> Optional logger for ActionType.as_task

docs/source/generating/actions.rst, docs/source/news.rst, eliot/__init__.py, eliot/_action.py, eliot/tests/test_action.py
=> Public APIs for current Action and Action's task UUID

docs/source/generating/actions.rst, docs/source/generating/twisted.rst, docs/source/news.rst, eliot/_action.py, eliot/tests/test_action.py
=> context() returns the Action

docs/source/generating/types.rst, docs/source/news.rst, eliot/_validation.py, eliot/tests/test_message.py, eliot/tests/test_validation.py
=> MessageType.log()

.style.yapf, docs/source/generating/twisted.rst, docs/source/news.rst, eliot/tests/test_twisted.py, eliot/twisted.py, tox.ini
=> Twisted.logger support, in both trial and explicit variants

docs/source/generating/twisted.rst, docs/source/news.rst, docs/source/outputting/output.rst, eliot/__init__.py, eliot/_output.py, eliot/tests/test_action.py, eliot/tests/test_api.py, eliot/tests/test_output.py, examples/journald.py
=> Buffer in memory before destinations are initially added

README.rst
=> Doc improvements

docs/source/news.rst, eliot/_action.py, eliot/tests/test_action.py
=> Accept text strings in Action.continue_task.

docs/source/generating/asyncio.rst, docs/source/generating/index.rst, docs/source/news.rst, eliot/__init__.py, eliot/_action.py, eliot/_asyncio.py, eliot/_message.py, eliot/tests/corotests.py, eliot/tests/test_action.py, eliot/tests/test_coroutines.py, eliot/tests/test_twisted.py, eliot/twisted.py, tox.ini
=> Coroutines support

README.rst, docs/source/index.rst, docs/source/quickstart.rst, examples/linkcheck.py
=> Nicer docs

docs/source/news.rst, docs/source/outputting/output.rst, eliot/_bytesjson.py, eliot/_output.py, eliot/filter.py, eliot/tests/test_output.py
=> Custom JSON encoder

docs/source/news.rst, eliot/_output.py
=> Nicer errors on JSON encoding failure.

docs/source/generating/asyncio.rst
=> asyncio doc typo fix: s/coruotine/coroutine/

docs/source/generating/index.rst, docs/source/generating/loglevels.rst, docs/source/news.rst, docs/source/reading/reading.rst
=> Document filtering logs

README.rst, docs/source/conf.py, docs/source/index.rst, eliot/tests/test_traceback.py, eliot/twisted.py, setup.py
=> ClusterHQ is dead

docs/source/news.rst, docs/source/outputting/elasticsearch.rst, docs/source/outputting/logstash_standalone.conf
=> Fix Logstash config

docs/source/generating/index.rst, docs/source/generating/migrating.rst, docs/source/news.rst, eliot/stdlib.py, eliot/tests/test_stdlib.py, examples/stdlib.py
=> Migrating to eliot

.travis.yml, README.rst, docs/source/index.rst, docs/source/news.rst, setup.py, tox.ini
=> Add support for 3.7

docs/source/news.rst, docs/source/reading/fields.rst, eliot/_message.py, eliot/tests/test_action.py, eliot/tests/test_message.py
=> All messages have either message_type or action_type

docs/source/conf.py, setup.py, tox.ini
=> Use RTD theme by default for better previewing.

docs/source/generating/errors.rst, docs/source/news.rst, docs/source/quickstart.rst, eliot/__init__.py, eliot/_errors.py, eliot/_output.py, eliot/_traceback.py, eliot/stdlib.py, eliot/tests/test_output.py, eliot/tests/test_stdlib.py, eliot/tests/test_testing.py, eliot/tests/test_traceback.py, eliot/tests/test_twisted.py
Fixes #321 
Fixes #298 
Fixes #322
=> Stdlib bridge logs tracebacks

docs/source/news.rst, eliot/_json.py, eliot/_output.py, eliot/tests/test_json.py, eliot/tests/test_output.py, tox.ini
=> NumPy serialization support

docs/source/news.rst, eliot/dask.py, eliot/testing.py, eliot/tests/test_dask.py, eliot/tests/test_testing.py, tox.ini
=> Basic Dask support

docs/source/generating/actions.rst, docs/source/news.rst, eliot/__init__.py, eliot/_action.py, eliot/_validation.py, eliot/tests/test_action.py, eliot/tests/test_journald.py, eliot/tests/test_message.py, eliot/tests/test_testing.py, eliot/tests/test_twisted.py, eliot/tests/test_validation.py, setup.py
=> log_call decorator

README.rst, docs/source/generating/asyncio.rst, docs/source/index.rst, eliot/tests/test_traceback.py, eliot/twisted.py, setup.py
=> Note repository has moved on GitHub.

eliot/_action.py, eliot/tests/test_action.py
=> More log call improvements

docs/source/news.rst, docs/source/reading/reading.rst, eliot/__init__.py, eliot/parse.py, eliot/tests/corotests.py, eliot/tests/test_action.py, eliot/tests/test_parse.py
Fixes #328.
@jonathanj could you take a look?
=> Public parser module

benchmarks/serialization.py, docs/source/news.rst, eliot/_action.py, eliot/_message.py, eliot/_output.py, eliot/tests/__init__.py, eliot/tests/test_action.py, setup.py
Was hoping speedups would obviate need for increasing deadline, but they didn't. On the plus side, it's faster now.
Fixes #359.
=> Fix tests on PyPy, and include some speedups

setup.py
=> Use version of boltons that has fix for imported type annotations

eliot/tests/test_twisted.py, eliot/twisted.py
=> Compatibility with Deferred.addCallbacks

docs/source/news.rst, eliot/__init__.py
=> Make ValidationError public

eliot/_output.py
=> Delete the extra definition

eliot/_traceback.py
=> More useful docstring for writeFailure

benchmarks/serialization.py
=> More realistic benchmark

docs/source/news.rst, eliot/_output.py, eliot/tests/test_output.py
=> Make MemoryLogger thread-safe

docs/source/news.rst, eliot/_output.py, eliot/testing.py, eliot/tests/test_output.py, eliot/tests/test_testing.py
=> Better error messages from @capture_logging and friends

docs/source/news.rst, eliot/__init__.py, eliot/_action.py, eliot/_asyncio.py, eliot/tests/corotests.py, eliot/tests/test_action.py
Prerequisite for #387.
Fixes #388.
=> Less buggy and more general sub-context mechanism

README.rst, docs/source/index.rst, docs/source/python2.rst, docs/source/quickstart.rst
=> Better pitch, and link to commercial support.

docs/source/news.rst, eliot/_traceback.py, eliot/_util.py, eliot/prettyprint.py, eliot/tests/test_pyinstaller.py, tox.ini
=> Support for PyInstaller

README.rst, docs/source/index.rst, docs/source/scientific-computing.rst, docs/source/usecases/index.rst
=> Highlight scientific computing

README.rst, docs/source/index.rst, docs/source/outputting/output.rst, docs/source/quickstart.rst
=> Highlight Trio and scientific computing.

docs/source/news.rst, eliot/_output.py, eliot/tests/test_output.py
=> Raise error if the log file is not writable.

.travis.yml, README.rst, docs/source/index.rst, docs/source/news.rst, tox.ini
=> PyPy3 support

docs/source/news.rst, docs/source/scientific-computing.rst, eliot/json.py, eliot/tests/test_json.py
=> Better support for large numpy arrays

.dir-locals.el, docs/source/news.rst, eliot/testing.py, eliot/tests/test_testing.py
=> Pass through *args and **kwargs from @capture_logging.

docs/source/news.rst, eliot/dask.py, tox.ini
=> Add support for dask 2.0

docs/source/news.rst, docs/source/reading/reading.rst, eliot/prettyprint.py, eliot/tests/test_prettyprint.py
=> Compact output for prettyprint

docs/source/news.rst, eliot/prettyprint.py, eliot/tests/test_prettyprint.py
=> Add support for local time zones.

docs/source/reading/reading.rst
=> #444: Fix bad rendering.

docs/source/news.rst, docs/source/scientific-computing.rst, eliot/dask.py, eliot/tests/test_dask.py, tox.ini
Fixes #446.
@mdwint could you try this out and see if solves your problem, and that the logs look as you'd expect?
=> #446: dask.persist() support.

.github/workflows/main.yml, README.rst, docs/source/index.rst, setup.py, tox.ini
=> Support for Python 3.9

eliot/tests/test_dask.py
=> Update tests to match latest Dask/Distributed

.github/workflows/main.yml, README.rst, docs/source/news.rst, docs/source/python2.rst, setup.py, tox.ini
=> Add support for 3.10

docs/source/news.rst, eliot/dask.py
=> Fix incompatibility with newer Dask
